[green_agent]
agentbeats_id = "019bb05a-4eea-74d1-8300-751194828e27"
env = {}

[[participants]]
agentbeats_id = "019bb093-36ec-74f2-94bb-379763cf5b43"
name = "role_1_name"
env = {}

[config]
# Add your assessment config here
num_tasks=2
